/**
 * Universal Database Restore Script (Node / TypeScript)
 *
 * Restores data from an SQL backup file generated by backup-db.ts or pg_dump.
 *
 * Usage:
 *   npx tsx scripts/restore-db.ts <backup_file.sql> [--yes]
 *   npm run db:restore -- <backup_file.sql>
 */

import { config } from 'dotenv'
import * as path from 'path'
import * as fs from 'fs'
import { Client } from 'pg'

config({ path: path.resolve(process.cwd(), '.env') })
if (!process.env.DATABASE_URL && !process.env.POSTGRES_URL) {
  config({ path: path.resolve(process.cwd(), '.env.local') })
}

const DB_URL = process.env.DATABASE_URL || process.env.POSTGRES_URL

if (!DB_URL) {
  console.error('❌ Error: DATABASE_URL is not set in environment or .env file.')
  process.exit(1)
}

const args = process.argv.slice(2)
const backupFile = args.find(a => !a.startsWith('-'))
const autoConfirm = args.includes('--yes') || args.includes('-y')

if (!backupFile) {
  console.error('Usage: npx tsx scripts/restore-db.ts <path_to_backup.sql> [--yes]\n')
  const backupDir = path.resolve(process.cwd(), 'backups')
  if (fs.existsSync(backupDir)) {
    console.log('Available backups in ./backups/:')
    const files = fs.readdirSync(backupDir).filter(f => f.endsWith('.sql')).sort().reverse()
    files.forEach(f => {
      const s = fs.statSync(path.join(backupDir, f))
      console.log(`  - backups/${f} (${(s.size / 1024).toFixed(1)} KB)`)
    })
  }
  process.exit(1)
}

const resolvedPath = path.resolve(process.cwd(), backupFile)
if (!fs.existsSync(resolvedPath)) {
  console.error(`❌ Error: Backup file not found at: ${resolvedPath}`)
  process.exit(1)
}

const stat = fs.statSync(resolvedPath)
if (stat.size === 0) {
  console.error(`❌ Error: Backup file is empty (0 bytes): ${resolvedPath}`)
  process.exit(1)
}

async function restore() {
  const host = DB_URL?.replace(/.*@([^:/]*).*/, '$1') || 'database'
  console.log('╔══════════════════════════════════════════╗')
  console.log('║      ⚠️  DATABASE RESTORE WARNING ⚠️      ║')
  console.log('╚══════════════════════════════════════════╝')
  console.log(`  Target Host: ${host}`)
  console.log(`  Backup File: ${resolvedPath} (${(stat.size / 1024).toFixed(1)} KB)`)
  console.log('')
  console.log('  This will restore the database to the state in the backup file.')

  if (!autoConfirm) {
    console.log('  Waiting 5 seconds before starting (Ctrl+C to abort)...')
    await new Promise(r => setTimeout(r, 5000))
  }

  console.log('\n🔄 Reading backup file...')
  const sql = fs.readFileSync(resolvedPath, 'utf-8')

  console.log('📡 Connecting to database...')
  const client = new Client({ connectionString: DB_URL })
  await client.connect()

  // Ensure public schema search path
  await client.query('SET search_path = public, pg_catalog;')

  try {
    console.log('🚀 Executing restore SQL script...')
    await client.query(sql)
    console.log('\n──────────────────────────────────────────')
    console.log('✅ Database restored successfully!')
    console.log(`📁 Source: ${resolvedPath}`)
    console.log('──────────────────────────────────────────')
  } catch (err: any) {
    console.error('❌ Restore failed:', err.message)
    process.exit(1)
  } finally {
    await client.end()
  }
}

restore().catch((err) => {
  console.error('❌ Restore failed:', err.message)
  process.exit(1)
})
