
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import { pgTable, index, uniqueIndex, foreignKey, integer, varchar, timestamp, serial, numeric, boolean, jsonb, type AnyPgColumn, pgEnum } from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['customer', 'artist', 'admin'])
export const enum_leads_event_type = pgEnum('enum_leads_event_type', ['bridal', 'engagement', 'baby-shower', 'family-function', 'festival', 'other'])
export const enum_leads_budget_range = pgEnum('enum_leads_budget_range', ['under-2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', 'above-50000', 'unsure'])
export const enum_leads_status = pgEnum('enum_leads_status', ['new', 'quotes-sent', 'accepted', 'booked', 'closed'])
export const enum_quotes_status = pgEnum('enum_quotes_status', ['pending', 'sent', 'viewed', 'accepted', 'rejected', 'expired', 'withdrawn'])
export const enum_bookings_event_type = pgEnum('enum_bookings_event_type', ['bridal', 'engagement', 'baby-shower', 'family-function', 'festival', 'other'])
export const enum_bookings_status = pgEnum('enum_bookings_status', ['new', 'contacted', 'confirmed', 'completed', 'cancelled'])

export const users_sessions = pgTable('users_sessions', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
  expiresAt: timestamp('expires_at', {mode: 'string',withTimezone: true,precision: 3}).notNull(),
}, (columns) => [
    index('users_sessions_order_idx').on(columns._order), index('users_sessions_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: varchar('name').notNull(),
  role: enum_users_role('role').notNull().default("customer"),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  email: varchar('email').notNull(),
  resetPasswordToken: varchar('reset_password_token'),
  resetPasswordExpiration: timestamp('reset_password_expiration', {mode: 'string',withTimezone: true,precision: 3}),
  salt: varchar('salt'),
  hash: varchar('hash'),
  loginAttempts: numeric('login_attempts', {mode: 'number'}).default(0),
  lockUntil: timestamp('lock_until', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt), index('users_created_at_idx').on(columns.createdAt), uniqueIndex('users_email_idx').on(columns.email),
]
)


export const media = pgTable('media', {
  id: serial('id').primaryKey(),
  alt: varchar('alt').notNull(),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  url: varchar('url'),
  thumbnailURL: varchar('thumbnail_u_r_l'),
  filename: varchar('filename'),
  mimeType: varchar('mime_type'),
  filesize: numeric('filesize', {mode: 'number'}),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  focalX: numeric('focal_x', {mode: 'number'}),
  focalY: numeric('focal_y', {mode: 'number'}),
}, (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt), index('media_created_at_idx').on(columns.createdAt), uniqueIndex('media_filename_idx').on(columns.filename),
]
)


export const services_points = pgTable('services_points', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  point: varchar('point').notNull(),
}, (columns) => [
    index('services_points_order_idx').on(columns._order), index('services_points_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services.id],
      name: 'services_points_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const services = pgTable('services', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug'),
  image: integer('image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  description: varchar('description').notNull(),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('services_slug_idx').on(columns.slug), index('services_image_idx').on(columns.image), index('services_updated_at_idx').on(columns.updatedAt), index('services_created_at_idx').on(columns.createdAt),
]
)


export const portfolio_categories = pgTable('portfolio_categories', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug'),
  description: varchar('description'),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('portfolio_categories_slug_idx').on(columns.slug), index('portfolio_categories_updated_at_idx').on(columns.updatedAt), index('portfolio_categories_created_at_idx').on(columns.createdAt),
]
)


export const portfolio_items = pgTable('portfolio_items', {
  id: serial('id').primaryKey(),
  image: integer('image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  category: integer('category_id').notNull().references(() => portfolio_categories.id, {
      onDelete: 'set null'
  }),
  altText: varchar('alt_text').notNull().default("Mehndi design image"),
  featured: boolean('featured').default(false),
  description: varchar('description'),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('portfolio_items_image_idx').on(columns.image), index('portfolio_items_category_idx').on(columns.category), index('portfolio_items_updated_at_idx').on(columns.updatedAt), index('portfolio_items_created_at_idx').on(columns.createdAt),
]
)


export const testimonials = pgTable('testimonials', {
  id: serial('id').primaryKey(),
  name: varchar('name').notNull(),
  text: varchar('text').notNull(),
  rating: numeric('rating', {mode: 'number'}).default(5),
  image: integer('image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('testimonials_image_idx').on(columns.image), index('testimonials_updated_at_idx').on(columns.updatedAt), index('testimonials_created_at_idx').on(columns.createdAt),
]
)


export const faq = pgTable('faq', {
  id: serial('id').primaryKey(),
  question: varchar('question').notNull(),
  answer: jsonb('answer').notNull(),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('faq_updated_at_idx').on(columns.updatedAt), index('faq_created_at_idx').on(columns.createdAt),
]
)


export const youtube_videos = pgTable('youtube_videos', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  videoId: varchar('video_id').notNull(),
  thumbnail: integer('thumbnail_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('youtube_videos_thumbnail_idx').on(columns.thumbnail), index('youtube_videos_updated_at_idx').on(columns.updatedAt), index('youtube_videos_created_at_idx').on(columns.createdAt),
]
)


export const static_pages = pgTable('static_pages', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug').notNull(),
  content: jsonb('content').notNull(),
  metaTitle: varchar('meta_title'),
  metaDescription: varchar('meta_description'),
  ogImage: integer('og_image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('static_pages_slug_idx').on(columns.slug), index('static_pages_og_image_idx').on(columns.ogImage), index('static_pages_updated_at_idx').on(columns.updatedAt), index('static_pages_created_at_idx').on(columns.createdAt),
]
)


export const artists_styles = pgTable('artists_styles', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  style: varchar('style').notNull(),
}, (columns) => [
    index('artists_styles_order_idx').on(columns._order), index('artists_styles_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [artists.id],
      name: 'artists_styles_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const artists_portfolio_images = pgTable('artists_portfolio_images', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  image: integer('image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  caption: varchar('caption'),
}, (columns) => [
    index('artists_portfolio_images_order_idx').on(columns._order), index('artists_portfolio_images_parent_id_idx').on(columns._parentID), index('artists_portfolio_images_image_idx').on(columns.image), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [artists.id],
      name: 'artists_portfolio_images_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const artists = pgTable('artists', {
  id: serial('id').primaryKey(),
  displayName: varchar('display_name').notNull(),
  slug: varchar('slug'),
  user: integer('user_id').references(() => users.id, {
      onDelete: 'set null'
  }),
  profilePhoto: integer('profile_photo_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  phone: varchar('phone').notNull(),
  whatsappNumber: varchar('whatsapp_number'),
  email: varchar('email'),
  bio: varchar('bio').notNull(),
  city: varchar('city').notNull().default("Ahmedabad"),
  area: varchar('area'),
  yearsOfExperience: numeric('years_of_experience', {mode: 'number'}),
  startingPrice: numeric('starting_price', {mode: 'number'}),
  verified: boolean('verified').default(false),
  rating: numeric('rating', {mode: 'number'}).default(0),
  reviewCount: numeric('review_count', {mode: 'number'}).default(0),
  order: numeric('order', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('artists_slug_idx').on(columns.slug), uniqueIndex('artists_user_idx').on(columns.user), index('artists_profile_photo_idx').on(columns.profilePhoto), index('artists_updated_at_idx').on(columns.updatedAt), index('artists_created_at_idx').on(columns.createdAt),
]
)


export const artists_rels = pgTable('artists_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  servicesID: integer('services_id'),
}, (columns) => [
    index('artists_rels_order_idx').on(columns.order), index('artists_rels_parent_idx').on(columns.parent), index('artists_rels_path_idx').on(columns.path), index('artists_rels_services_id_idx').on(columns.servicesID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [artists.id],
      name: 'artists_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'artists_rels_services_fk'
    }).onDelete('cascade'),
]
)


export const leads = pgTable('leads', {
  id: serial('id').primaryKey(),
  customerName: varchar('customer_name').notNull(),
  customerPhone: varchar('customer_phone').notNull(),
  customerEmail: varchar('customer_email'),
  eventType: enum_leads_event_type('event_type').notNull(),
  eventDate: timestamp('event_date', {mode: 'string',withTimezone: true,precision: 3}).notNull(),
  eventLocation: varchar('event_location').notNull(),
  guestCount: numeric('guest_count', {mode: 'number'}),
  budgetRange: enum_leads_budget_range('budget_range'),
  serviceType: integer('service_type_id').references(() => services.id, {
      onDelete: 'set null'
  }),
  designStyle: varchar('design_style'),
  additionalNotes: varchar('additional_notes'),
  acceptedQuote: integer('accepted_quote_id').references((): AnyPgColumn => quotes.id, {
      onDelete: 'set null'
  }),
  status: enum_leads_status('status').default("new"),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('leads_service_type_idx').on(columns.serviceType), index('leads_accepted_quote_idx').on(columns.acceptedQuote), index('leads_updated_at_idx').on(columns.updatedAt), index('leads_created_at_idx').on(columns.createdAt),
]
)


export const leads_rels = pgTable('leads_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  artistsID: integer('artists_id'),
}, (columns) => [
    index('leads_rels_order_idx').on(columns.order), index('leads_rels_parent_idx').on(columns.parent), index('leads_rels_path_idx').on(columns.path), index('leads_rels_artists_id_idx').on(columns.artistsID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [leads.id],
      name: 'leads_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['artistsID']],
      foreignColumns: [artists.id],
      name: 'leads_rels_artists_fk'
    }).onDelete('cascade'),
]
)


export const quotes = pgTable('quotes', {
  id: serial('id').primaryKey(),
  lead: integer('lead_id').notNull().references((): AnyPgColumn => leads.id, {
      onDelete: 'set null'
  }),
  artist: integer('artist_id').notNull().references(() => artists.id, {
      onDelete: 'set null'
  }),
  amount: numeric('amount', {mode: 'number'}).notNull(),
  message: varchar('message'),
  estimatedHours: numeric('estimated_hours', {mode: 'number'}),
  travelFee: numeric('travel_fee', {mode: 'number'}).default(0),
  numberOfArtists: numeric('number_of_artists', {mode: 'number'}).default(1),
  validUntil: timestamp('valid_until', {mode: 'string',withTimezone: true,precision: 3}),
  status: enum_quotes_status('status').default("pending"),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('quotes_lead_idx').on(columns.lead), index('quotes_artist_idx').on(columns.artist), index('quotes_updated_at_idx').on(columns.updatedAt), index('quotes_created_at_idx').on(columns.createdAt),
]
)


export const bookings = pgTable('bookings', {
  id: serial('id').primaryKey(),
  name: varchar('name').notNull(),
  phone: varchar('phone').notNull(),
  email: varchar('email'),
  eventType: enum_bookings_event_type('event_type').notNull(),
  eventDate: timestamp('event_date', {mode: 'string',withTimezone: true,precision: 3}).notNull(),
  location: varchar('location').notNull(),
  guestCount: numeric('guest_count', {mode: 'number'}),
  designStyle: varchar('design_style'),
  message: varchar('message'),
  artist: integer('artist_id').references(() => artists.id, {
      onDelete: 'set null'
  }),
  status: enum_bookings_status('status').default("new"),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('bookings_artist_idx').on(columns.artist), index('bookings_updated_at_idx').on(columns.updatedAt), index('bookings_created_at_idx').on(columns.createdAt),
]
)


export const payload_kv = pgTable('payload_kv', {
  id: serial('id').primaryKey(),
  key: varchar('key').notNull(),
  data: jsonb('data').notNull(),
}, (columns) => [
    uniqueIndex('payload_kv_key_idx').on(columns.key),
]
)


export const payload_locked_documents = pgTable('payload_locked_documents', {
  id: serial('id').primaryKey(),
  globalSlug: varchar('global_slug'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug), index('payload_locked_documents_updated_at_idx').on(columns.updatedAt), index('payload_locked_documents_created_at_idx').on(columns.createdAt),
]
)


export const payload_locked_documents_rels = pgTable('payload_locked_documents_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  usersID: integer('users_id'),
  mediaID: integer('media_id'),
  servicesID: integer('services_id'),
  'portfolio-categoriesID': integer('portfolio_categories_id'),
  'portfolio-itemsID': integer('portfolio_items_id'),
  testimonialsID: integer('testimonials_id'),
  faqID: integer('faq_id'),
  'youtube-videosID': integer('youtube_videos_id'),
  'static-pagesID': integer('static_pages_id'),
  artistsID: integer('artists_id'),
  leadsID: integer('leads_id'),
  quotesID: integer('quotes_id'),
  bookingsID: integer('bookings_id'),
}, (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order), index('payload_locked_documents_rels_parent_idx').on(columns.parent), index('payload_locked_documents_rels_path_idx').on(columns.path), index('payload_locked_documents_rels_users_id_idx').on(columns.usersID), index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID), index('payload_locked_documents_rels_services_id_idx').on(columns.servicesID), index('payload_locked_documents_rels_portfolio_categories_id_idx').on(columns['portfolio-categoriesID']), index('payload_locked_documents_rels_portfolio_items_id_idx').on(columns['portfolio-itemsID']), index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID), index('payload_locked_documents_rels_faq_id_idx').on(columns.faqID), index('payload_locked_documents_rels_youtube_videos_id_idx').on(columns['youtube-videosID']), index('payload_locked_documents_rels_static_pages_id_idx').on(columns['static-pagesID']), index('payload_locked_documents_rels_artists_id_idx').on(columns.artistsID), index('payload_locked_documents_rels_leads_id_idx').on(columns.leadsID), index('payload_locked_documents_rels_quotes_id_idx').on(columns.quotesID), index('payload_locked_documents_rels_bookings_id_idx').on(columns.bookingsID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'payload_locked_documents_rels_services_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['portfolio-categoriesID']],
      foreignColumns: [portfolio_categories.id],
      name: 'payload_locked_documents_rels_portfolio_categories_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['portfolio-itemsID']],
      foreignColumns: [portfolio_items.id],
      name: 'payload_locked_documents_rels_portfolio_items_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['faqID']],
      foreignColumns: [faq.id],
      name: 'payload_locked_documents_rels_faq_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['youtube-videosID']],
      foreignColumns: [youtube_videos.id],
      name: 'payload_locked_documents_rels_youtube_videos_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['static-pagesID']],
      foreignColumns: [static_pages.id],
      name: 'payload_locked_documents_rels_static_pages_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['artistsID']],
      foreignColumns: [artists.id],
      name: 'payload_locked_documents_rels_artists_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['leadsID']],
      foreignColumns: [leads.id],
      name: 'payload_locked_documents_rels_leads_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['quotesID']],
      foreignColumns: [quotes.id],
      name: 'payload_locked_documents_rels_quotes_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['bookingsID']],
      foreignColumns: [bookings.id],
      name: 'payload_locked_documents_rels_bookings_fk'
    }).onDelete('cascade'),
]
)


export const payload_preferences = pgTable('payload_preferences', {
  id: serial('id').primaryKey(),
  key: varchar('key'),
  value: jsonb('value'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_preferences_key_idx').on(columns.key), index('payload_preferences_updated_at_idx').on(columns.updatedAt), index('payload_preferences_created_at_idx').on(columns.createdAt),
]
)


export const payload_preferences_rels = pgTable('payload_preferences_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order), index('payload_preferences_rels_parent_idx').on(columns.parent), index('payload_preferences_rels_path_idx').on(columns.path), index('payload_preferences_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_migrations = pgTable('payload_migrations', {
  id: serial('id').primaryKey(),
  name: varchar('name'),
  batch: numeric('batch', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt), index('payload_migrations_created_at_idx').on(columns.createdAt),
]
)


export const site_settings = pgTable('site_settings', {
  id: serial('id').primaryKey(),
  businessName: varchar('business_name').notNull().default("Shiva Mehndi Art"),
  founderName: varchar('founder_name').notNull().default("Bhumi Chanpura"),
  phone: varchar('phone').notNull().default("+91 8469662012"),
  email: varchar('email').notNull().default("bhumichanpura1234@gmail.com"),
  address: varchar('address').notNull().default("C-206 Neelkanth Homes, Chandlodiya, Ahmedabad 382481"),
  tagline: varchar('tagline').default("Premium Mehndi Artist – Ahmedabad"),
  facebookUrl: varchar('facebook_url').default("https://facebook.com/"),
  instagramUrl: varchar('instagram_url').default("https://instagram.com/"),
  youtubeUrl: varchar('youtube_url').default("https://youtube.com/"),
  googleMapUrl: varchar('google_map_url').default("https://maps.google.com/"),
  bookingFormUrl: varchar('booking_form_url').notNull().default("https://docs.google.com/forms/d/e/1FAIpQLSeE8i0kMqjmb8jjVLc_YgNGR8q413ZdgEXQbzNZdULpf9r8MA/viewform"),
  whatsappNumber: varchar('whatsapp_number').default("+918469662012"),
  defaultMetaTitle: varchar('default_meta_title').default("Shiva Mehndi Art — Premium Mehndi Artist in Ahmedabad"),
  defaultMetaDescription: varchar('default_meta_description').default("Shiva Mehndi Art by Bhumi Chanpura offers premium bridal, engagement, and festive mehndi in Ahmedabad. Home service available."),
  defaultOgImage: integer('default_og_image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('site_settings_default_og_image_idx').on(columns.defaultOgImage),
]
)


export const header_footer_nav_links = pgTable('header_footer_nav_links', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  label: varchar('label').notNull(),
  path: varchar('path').notNull(),
}, (columns) => [
    index('header_footer_nav_links_order_idx').on(columns._order), index('header_footer_nav_links_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header_footer.id],
      name: 'header_footer_nav_links_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const header_footer_footer_links = pgTable('header_footer_footer_links', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  label: varchar('label').notNull(),
  path: varchar('path').notNull(),
}, (columns) => [
    index('header_footer_footer_links_order_idx').on(columns._order), index('header_footer_footer_links_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header_footer.id],
      name: 'header_footer_footer_links_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const header_footer = pgTable('header_footer', {
  id: serial('id').primaryKey(),
  logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  footerTagline: varchar('footer_tagline').default("Premium mehndi artistry by Bhumi Chanpura, based in Chandlodiya, Ahmedabad. Bridal, engagement, festive, and home-service mehndi across the city."),
  copyrightText: varchar('copyright_text').default("© Shiva Mehndi Art. All rights reserved."),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('header_footer_logo_idx').on(columns.logo),
]
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
    }),
      }))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
            relationName: 'sessions',
    }),
      }))
export const relations_media = relations(media, () => ({
  
      }))
export const relations_services_points = relations(services_points, ({ one }) => ({
  _parentID: one(services, {
    
    fields: [services_points._parentID],
    references: [services.id],
    relationName: 'points',
    }),
      }))
export const relations_services = relations(services, ({ one, many }) => ({
  image: one(media, {
    
    fields: [services.image],
    references: [media.id],
    relationName: 'image',
    }),
    points: many(services_points, {
            relationName: 'points',
    }),
      }))
export const relations_portfolio_categories = relations(portfolio_categories, () => ({
  
      }))
export const relations_portfolio_items = relations(portfolio_items, ({ one }) => ({
  image: one(media, {
    
    fields: [portfolio_items.image],
    references: [media.id],
    relationName: 'image',
    }),
    category: one(portfolio_categories, {
    
    fields: [portfolio_items.category],
    references: [portfolio_categories.id],
    relationName: 'category',
    }),
      }))
export const relations_testimonials = relations(testimonials, ({ one }) => ({
  image: one(media, {
    
    fields: [testimonials.image],
    references: [media.id],
    relationName: 'image',
    }),
      }))
export const relations_faq = relations(faq, () => ({
  
      }))
export const relations_youtube_videos = relations(youtube_videos, ({ one }) => ({
  thumbnail: one(media, {
    
    fields: [youtube_videos.thumbnail],
    references: [media.id],
    relationName: 'thumbnail',
    }),
      }))
export const relations_static_pages = relations(static_pages, ({ one }) => ({
  ogImage: one(media, {
    
    fields: [static_pages.ogImage],
    references: [media.id],
    relationName: 'ogImage',
    }),
      }))
export const relations_artists_styles = relations(artists_styles, ({ one }) => ({
  _parentID: one(artists, {
    
    fields: [artists_styles._parentID],
    references: [artists.id],
    relationName: 'styles',
    }),
      }))
export const relations_artists_portfolio_images = relations(artists_portfolio_images, ({ one }) => ({
  _parentID: one(artists, {
    
    fields: [artists_portfolio_images._parentID],
    references: [artists.id],
    relationName: 'portfolioImages',
    }),
    image: one(media, {
    
    fields: [artists_portfolio_images.image],
    references: [media.id],
    relationName: 'image',
    }),
      }))
export const relations_artists_rels = relations(artists_rels, ({ one }) => ({
  parent: one(artists, {
    
    fields: [artists_rels.parent],
    references: [artists.id],
    relationName: '_rels',
    }),
    servicesID: one(services, {
    
    fields: [artists_rels.servicesID],
    references: [services.id],
    relationName: 'services',
    }),
      }))
export const relations_artists = relations(artists, ({ one, many }) => ({
  user: one(users, {
    
    fields: [artists.user],
    references: [users.id],
    relationName: 'user',
    }),
    profilePhoto: one(media, {
    
    fields: [artists.profilePhoto],
    references: [media.id],
    relationName: 'profilePhoto',
    }),
    styles: many(artists_styles, {
            relationName: 'styles',
    }),
    portfolioImages: many(artists_portfolio_images, {
            relationName: 'portfolioImages',
    }),
    _rels: many(artists_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_leads_rels = relations(leads_rels, ({ one }) => ({
  parent: one(leads, {
    
    fields: [leads_rels.parent],
    references: [leads.id],
    relationName: '_rels',
    }),
    artistsID: one(artists, {
    
    fields: [leads_rels.artistsID],
    references: [artists.id],
    relationName: 'artists',
    }),
      }))
export const relations_leads = relations(leads, ({ one, many }) => ({
  serviceType: one(services, {
    
    fields: [leads.serviceType],
    references: [services.id],
    relationName: 'serviceType',
    }),
    acceptedQuote: one(quotes, {
    
    fields: [leads.acceptedQuote],
    references: [quotes.id],
    relationName: 'acceptedQuote',
    }),
    _rels: many(leads_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_quotes = relations(quotes, ({ one }) => ({
  lead: one(leads, {
    
    fields: [quotes.lead],
    references: [leads.id],
    relationName: 'lead',
    }),
    artist: one(artists, {
    
    fields: [quotes.artist],
    references: [artists.id],
    relationName: 'artist',
    }),
      }))
export const relations_bookings = relations(bookings, ({ one }) => ({
  artist: one(artists, {
    
    fields: [bookings.artist],
    references: [artists.id],
    relationName: 'artist',
    }),
      }))
export const relations_payload_kv = relations(payload_kv, () => ({
  
      }))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
    mediaID: one(media, {
    
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
    }),
    servicesID: one(services, {
    
    fields: [payload_locked_documents_rels.servicesID],
    references: [services.id],
    relationName: 'services',
    }),
    'portfolio-categoriesID': one(portfolio_categories, {
    
    fields: [payload_locked_documents_rels['portfolio-categoriesID']],
    references: [portfolio_categories.id],
    relationName: 'portfolio-categories',
    }),
    'portfolio-itemsID': one(portfolio_items, {
    
    fields: [payload_locked_documents_rels['portfolio-itemsID']],
    references: [portfolio_items.id],
    relationName: 'portfolio-items',
    }),
    testimonialsID: one(testimonials, {
    
    fields: [payload_locked_documents_rels.testimonialsID],
    references: [testimonials.id],
    relationName: 'testimonials',
    }),
    faqID: one(faq, {
    
    fields: [payload_locked_documents_rels.faqID],
    references: [faq.id],
    relationName: 'faq',
    }),
    'youtube-videosID': one(youtube_videos, {
    
    fields: [payload_locked_documents_rels['youtube-videosID']],
    references: [youtube_videos.id],
    relationName: 'youtube-videos',
    }),
    'static-pagesID': one(static_pages, {
    
    fields: [payload_locked_documents_rels['static-pagesID']],
    references: [static_pages.id],
    relationName: 'static-pages',
    }),
    artistsID: one(artists, {
    
    fields: [payload_locked_documents_rels.artistsID],
    references: [artists.id],
    relationName: 'artists',
    }),
    leadsID: one(leads, {
    
    fields: [payload_locked_documents_rels.leadsID],
    references: [leads.id],
    relationName: 'leads',
    }),
    quotesID: one(quotes, {
    
    fields: [payload_locked_documents_rels.quotesID],
    references: [quotes.id],
    relationName: 'quotes',
    }),
    bookingsID: one(bookings, {
    
    fields: [payload_locked_documents_rels.bookingsID],
    references: [bookings.id],
    relationName: 'bookings',
    }),
      }))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_migrations = relations(payload_migrations, () => ({
  
      }))
export const relations_site_settings = relations(site_settings, ({ one }) => ({
  defaultOgImage: one(media, {
    
    fields: [site_settings.defaultOgImage],
    references: [media.id],
    relationName: 'defaultOgImage',
    }),
      }))
export const relations_header_footer_nav_links = relations(header_footer_nav_links, ({ one }) => ({
  _parentID: one(header_footer, {
    
    fields: [header_footer_nav_links._parentID],
    references: [header_footer.id],
    relationName: 'navLinks',
    }),
      }))
export const relations_header_footer_footer_links = relations(header_footer_footer_links, ({ one }) => ({
  _parentID: one(header_footer, {
    
    fields: [header_footer_footer_links._parentID],
    references: [header_footer.id],
    relationName: 'footerLinks',
    }),
      }))
export const relations_header_footer = relations(header_footer, ({ one, many }) => ({
  logo: one(media, {
    
    fields: [header_footer.logo],
    references: [media.id],
    relationName: 'logo',
    }),
    navLinks: many(header_footer_nav_links, {
            relationName: 'navLinks',
    }),
    footerLinks: many(header_footer_footer_links, {
            relationName: 'footerLinks',
    }),
      }))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_leads_event_type: typeof enum_leads_event_type
  enum_leads_budget_range: typeof enum_leads_budget_range
  enum_leads_status: typeof enum_leads_status
  enum_quotes_status: typeof enum_quotes_status
  enum_bookings_event_type: typeof enum_bookings_event_type
  enum_bookings_status: typeof enum_bookings_status
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  services_points: typeof services_points
  services: typeof services
  portfolio_categories: typeof portfolio_categories
  portfolio_items: typeof portfolio_items
  testimonials: typeof testimonials
  faq: typeof faq
  youtube_videos: typeof youtube_videos
  static_pages: typeof static_pages
  artists_styles: typeof artists_styles
  artists_portfolio_images: typeof artists_portfolio_images
  artists: typeof artists
  artists_rels: typeof artists_rels
  leads: typeof leads
  leads_rels: typeof leads_rels
  quotes: typeof quotes
  bookings: typeof bookings
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_settings: typeof site_settings
  header_footer_nav_links: typeof header_footer_nav_links
  header_footer_footer_links: typeof header_footer_footer_links
  header_footer: typeof header_footer
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_services_points: typeof relations_services_points
  relations_services: typeof relations_services
  relations_portfolio_categories: typeof relations_portfolio_categories
  relations_portfolio_items: typeof relations_portfolio_items
  relations_testimonials: typeof relations_testimonials
  relations_faq: typeof relations_faq
  relations_youtube_videos: typeof relations_youtube_videos
  relations_static_pages: typeof relations_static_pages
  relations_artists_styles: typeof relations_artists_styles
  relations_artists_portfolio_images: typeof relations_artists_portfolio_images
  relations_artists_rels: typeof relations_artists_rels
  relations_artists: typeof relations_artists
  relations_leads_rels: typeof relations_leads_rels
  relations_leads: typeof relations_leads
  relations_quotes: typeof relations_quotes
  relations_bookings: typeof relations_bookings
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_settings: typeof relations_site_settings
  relations_header_footer_nav_links: typeof relations_header_footer_nav_links
  relations_header_footer_footer_links: typeof relations_header_footer_footer_links
  relations_header_footer: typeof relations_header_footer
}
    

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
    