/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'portfolio-categories': PortfolioCategory;
    'portfolio-items': PortfolioItem;
    testimonials: Testimonial;
    faq: Faq;
    'youtube-videos': YoutubeVideo;
    'static-pages': StaticPage;
    artists: Artist;
    leads: Lead;
    quotes: Quote;
    bookings: Booking;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    'portfolio-items': PortfolioItemsSelect<false> | PortfolioItemsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'youtube-videos': YoutubeVideosSelect<false> | YoutubeVideosSelect<true>;
    'static-pages': StaticPagesSelect<false> | StaticPagesSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'header-footer': HeaderFooter;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-footer': HeaderFooterSelect<false> | HeaderFooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'customer' | 'artist' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug?: string | null;
  image?: (number | null) | Media;
  description: string;
  points?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items".
 */
export interface PortfolioItem {
  id: number;
  image: number | Media;
  category: number | PortfolioCategory;
  altText: string;
  featured?: boolean | null;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  text: string;
  rating?: number | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-videos".
 */
export interface YoutubeVideo {
  id: number;
  title: string;
  /**
   * The YouTube video ID (e.g., dQw4w9WgXcQ)
   */
  videoId: string;
  thumbnail?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages".
 */
export interface StaticPage {
  id: number;
  title: string;
  /**
   * URL path (e.g., /bridal-mehndi)
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  displayName: string;
  slug?: string | null;
  user?: (number | null) | User;
  profilePhoto?: (number | null) | Media;
  phone: string;
  whatsappNumber?: string | null;
  email?: string | null;
  bio: string;
  city: string;
  area?: string | null;
  yearsOfExperience?: number | null;
  /**
   * Default pricing model
   */
  priceType?: ('package' | 'hourly' | 'per_person' | 'custom_quote') | null;
  /**
   * Starting price in INR for public display (e.g. 2000)
   */
  startingPrice?: number | null;
  /**
   * Dates when this artist is unavailable for bookings
   */
  unavailableDates?:
    | {
        date: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  services?: (number | Service)[] | null;
  styles?:
    | {
        style: string;
        id?: string | null;
      }[]
    | null;
  portfolioImages?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  verified?: boolean | null;
  approvalStatus?: ('pending' | 'approved' | 'rejected' | 'suspended') | null;
  verificationStatus?: ('unverified' | 'verified') | null;
  rating?: number | null;
  reviewCount?: number | null;
  isFeatured?: boolean | null;
  featuredUntil?: string | null;
  subscriptionPlan?: ('free' | 'basic' | 'premium') | null;
  subscriptionExpiresAt?: string | null;
  /**
   * Free: 10, Basic: 25, Premium: 50
   */
  maxPortfolioItems?: number | null;
  profileViews?: number | null;
  leadsReceived?: number | null;
  quotesSent?: number | null;
  bookingsWon?: number | null;
  /**
   * Total earnings in INR from completed bookings
   */
  totalEarnings?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  customerName: string;
  customerPhone: string;
  customerEmail?: string | null;
  eventType: 'bridal' | 'engagement' | 'baby-shower' | 'family-function' | 'festival' | 'other';
  eventDate: string;
  eventLocation: string;
  guestCount?: number | null;
  budgetRange?:
    | ('under-2000' | '2000-5000' | '5000-10000' | '10000-20000' | '20000-50000' | 'above-50000' | 'unsure')
    | null;
  serviceType?: (number | null) | Service;
  designStyle?: string | null;
  additionalNotes?: string | null;
  matchedArtists?: (number | Artist)[] | null;
  acceptedQuote?: (number | null) | Quote;
  status?:
    | (
        | 'new'
        | 'reviewing'
        | 'artists_matched'
        | 'quotes_received'
        | 'customer_contacted'
        | 'artist_selected'
        | 'booking_pending'
        | 'booked'
        | 'lost'
        | 'closed'
      )
    | null;
  lostReason?: string | null;
  assignedAdmin?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  lead: number | Lead;
  artist: number | Artist;
  priceType?: ('package' | 'hourly' | 'per_person' | 'custom_quote') | null;
  unitRate?: number | null;
  units?: number | null;
  amount: number;
  message?: string | null;
  estimatedHours?: number | null;
  travelFee?: number | null;
  numberOfArtists?: number | null;
  validUntil?: string | null;
  status?: ('pending' | 'sent' | 'viewed' | 'accepted' | 'rejected' | 'expired' | 'withdrawn') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  eventType: 'bridal' | 'engagement' | 'baby-shower' | 'family-function' | 'festival' | 'other';
  eventDate: string;
  location: string;
  guestCount?: number | null;
  designStyle?: string | null;
  message?: string | null;
  lead?: (number | null) | Lead;
  quote?: (number | null) | Quote;
  artist?: (number | null) | Artist;
  /**
   * Manage multiple artists for large events or group functions
   */
  assignedArtists?:
    | {
        artist: number | Artist;
        role?: ('lead' | 'assistant' | 'member') | null;
        status?: ('pending' | 'accepted' | 'declined') | null;
        declineReason?: string | null;
        fee?: number | null;
        id?: string | null;
      }[]
    | null;
  totalAmount?: number | null;
  advanceAmount?: number | null;
  remainingAmount?: number | null;
  platformFee?: number | null;
  artistAmount?: number | null;
  paymentStatus?: ('unpaid' | 'pending' | 'partially_paid' | 'paid' | 'refunded') | null;
  paymentMethod?: ('cash' | 'upi' | 'bank_transfer' | 'online') | null;
  paymentReference?: string | null;
  status?:
    | ('requested' | 'artist_pending' | 'confirmed' | 'in_progress' | 'completed' | 'declined' | 'cancelled')
    | null;
  declineReason?: string | null;
  cancelledBy?: ('customer' | 'artist' | 'admin' | 'system') | null;
  cancellationReason?: string | null;
  cancelledAt?: string | null;
  refundAmount?: number | null;
  refundStatus?: ('pending' | 'processing' | 'refunded' | 'denied') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  user: number | User;
  customerName: string;
  booking: number | Booking;
  artist: number | Artist;
  rating: number;
  title?: string | null;
  text: string;
  /**
   * Set to true if the review is from a completed booking
   */
  verifiedBooking?: boolean | null;
  helpfulCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'portfolio-items';
        value: number | PortfolioItem;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'youtube-videos';
        value: number | YoutubeVideo;
      } | null)
    | ({
        relationTo: 'static-pages';
        value: number | StaticPage;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  description?: T;
  points?:
    | T
    | {
        point?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items_select".
 */
export interface PortfolioItemsSelect<T extends boolean = true> {
  image?: T;
  category?: T;
  altText?: T;
  featured?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  text?: T;
  rating?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "youtube-videos_select".
 */
export interface YoutubeVideosSelect<T extends boolean = true> {
  title?: T;
  videoId?: T;
  thumbnail?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  user?: T;
  profilePhoto?: T;
  phone?: T;
  whatsappNumber?: T;
  email?: T;
  bio?: T;
  city?: T;
  area?: T;
  yearsOfExperience?: T;
  priceType?: T;
  startingPrice?: T;
  unavailableDates?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  services?: T;
  styles?:
    | T
    | {
        style?: T;
        id?: T;
      };
  portfolioImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  verified?: T;
  approvalStatus?: T;
  verificationStatus?: T;
  rating?: T;
  reviewCount?: T;
  isFeatured?: T;
  featuredUntil?: T;
  subscriptionPlan?: T;
  subscriptionExpiresAt?: T;
  maxPortfolioItems?: T;
  profileViews?: T;
  leadsReceived?: T;
  quotesSent?: T;
  bookingsWon?: T;
  totalEarnings?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  eventType?: T;
  eventDate?: T;
  eventLocation?: T;
  guestCount?: T;
  budgetRange?: T;
  serviceType?: T;
  designStyle?: T;
  additionalNotes?: T;
  matchedArtists?: T;
  acceptedQuote?: T;
  status?: T;
  lostReason?: T;
  assignedAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  lead?: T;
  artist?: T;
  priceType?: T;
  unitRate?: T;
  units?: T;
  amount?: T;
  message?: T;
  estimatedHours?: T;
  travelFee?: T;
  numberOfArtists?: T;
  validUntil?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  eventType?: T;
  eventDate?: T;
  location?: T;
  guestCount?: T;
  designStyle?: T;
  message?: T;
  lead?: T;
  quote?: T;
  artist?: T;
  assignedArtists?:
    | T
    | {
        artist?: T;
        role?: T;
        status?: T;
        declineReason?: T;
        fee?: T;
        id?: T;
      };
  totalAmount?: T;
  advanceAmount?: T;
  remainingAmount?: T;
  platformFee?: T;
  artistAmount?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  paymentReference?: T;
  status?: T;
  declineReason?: T;
  cancelledBy?: T;
  cancellationReason?: T;
  cancelledAt?: T;
  refundAmount?: T;
  refundStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  customerName?: T;
  booking?: T;
  artist?: T;
  rating?: T;
  title?: T;
  text?: T;
  verifiedBooking?: T;
  helpfulCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  founderName: string;
  phone: string;
  email: string;
  address: string;
  tagline?: string | null;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  youtubeUrl?: string | null;
  googleMapUrl?: string | null;
  bookingFormUrl: string;
  whatsappNumber?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-footer".
 */
export interface HeaderFooter {
  id: number;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  footerTagline?: string | null;
  copyrightText?: string | null;
  footerLinks?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  founderName?: T;
  phone?: T;
  email?: T;
  address?: T;
  tagline?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  youtubeUrl?: T;
  googleMapUrl?: T;
  bookingFormUrl?: T;
  whatsappNumber?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-footer_select".
 */
export interface HeaderFooterSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  footerTagline?: T;
  copyrightText?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}